# Generated by Django 3.2 on 2023-01-04 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_answer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('Answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmark.answer')),
            ],
        ),
    ]
